---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords: clone strategy 
summary: Wenn Sie eine Klonstrategie definieren, können Sie Ihre Datenbank erfolgreich klonen. 
---
= Definieren Sie eine Klonstrategie für SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine Klonstrategie definieren, können Sie Ihre Datenbank erfolgreich klonen.

. Prüfen Sie die Einschränkungen hinsichtlich von Klonvorgängen.
. Legen Sie den für Sie erforderlichen Klontyp fest.




== Einschränkungen von Klonvorgängen

Die Einschränkungen von Klonvorgängen sollten Sie beachten, bevor Sie die Datenbanken klonen.

* Wenn Sie eine Version von Oracle von 11.2.0.4 bis 12.1.0.1 verwenden, befindet sich der Klonvorgang in
Status Hung, wenn Sie den Befehl „_renamedg_“ ausführen. Sie können den Oracle Patch 19544733 anwenden
Um dieses Problem zu beheben.
* Klonen von Datenbanken aus einer LUN, die direkt an einen Host angebunden ist (beispielsweise mittels
Microsoft iSCSI Initiator auf einem Windows Host) zu einer VMDK oder einem RDM LUN auf dem gleichen
Windows-Host oder ein anderer Windows-Host oder umgekehrt wird nicht unterstützt.
* Das Stammverzeichnis des Volume-Bereitstellungspunkts kann kein freigegebenes Verzeichnis sein.
* Wenn Sie eine LUN verschieben, die einen Klon in ein neues Volume enthält, kann der Klon nicht gelöscht werden.




== Typen von Klonvorgängen

Sie können SnapCenter verwenden, um ein Backup einer SQL Server Datenbank oder eine Produktionsdatenbank zu klonen.

* Klonen aus einem Datenbank-Backup
+
Die geklonte Datenbank dient als Basis für die Entwicklung neuer Applikationen und isoliert Daten
Anwendungsfehler, die in der Produktionsumgebung auftreten. Darüber hinaus kann die geklonte Datenbank verwendet werden
Wird für die Wiederherstellung nach Soft-Datenbank-Fehlern verwendet.

* Lebenszyklus von Klonen
+
Sie können SnapCenter verwenden, um wiederkehrende Klonjobs zu planen, die bei der Produktion stattfinden
Datenbank ist nicht belegt.


